export const JOB_MESSAGE_PARSER_TOKEN = Symbol("JOB_MESSAGE_PARSER_TOKEN");

export const JOB_MESSAGE_IMPORT_MAX_INPUT_CHARS = 20_000;

export const JOB_MESSAGE_IMPORT_SOURCE_CHANNEL = "WHATSAPP" as const;

