ALTER TABLE "trips"
ADD COLUMN IF NOT EXISTS "trailerParkingLat" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "trailerParkingLng" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "trailerParkedAt" TIMESTAMP(3);
