-- AlterEnum
ALTER TYPE "WarehouseJobType" ADD VALUE 'STUFFING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'UNSTUFFING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'LASHING_CHOKING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'PALLETIZING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'PACKAGING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'CRATING';
ALTER TYPE "WarehouseJobType" ADD VALUE 'STORAGE';
ALTER TYPE "WarehouseJobType" ADD VALUE 'PICK_AND_PACK';
